modLoader = "javafml" #mandatory
loaderVersion = "[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "okzoomer" #mandatory
version = "${version}" #mandatory
displayName = "OkZoomer" #mandatory
logoFile = "okzoomer.png"
authors = "Matyrobbrt" #optional
description = '''
Adds a highly-configurable zoom key for Forge. The zoom is yours!
'''
credits = "EnnuiL, for the Fabric mod"
[[dependencies.okzoomer]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[41.1.0,)" #mandatory
ordering = "NONE"
side = "SERVER"
[[dependencies.okzoomer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"